workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120 
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.aventri.guide
      vars:
        APP_ID: 1111111111 # <-- Put your APP ID here
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
        ignore_failure: true
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa 
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    